# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from traxxas_control/servo_esc_coeffs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class servo_esc_coeffs(genpy.Message):
  _md5sum = "2d202238d5f284960838988ffb4a6570"
  _type = "traxxas_control/servo_esc_coeffs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 servo_neutral
int32 esc_neutral

int32 angle_mult
int32 throt_mult
"""
  __slots__ = ['servo_neutral','esc_neutral','angle_mult','throt_mult']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servo_neutral,esc_neutral,angle_mult,throt_mult

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(servo_esc_coeffs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servo_neutral is None:
        self.servo_neutral = 0
      if self.esc_neutral is None:
        self.esc_neutral = 0
      if self.angle_mult is None:
        self.angle_mult = 0
      if self.throt_mult is None:
        self.throt_mult = 0
    else:
      self.servo_neutral = 0
      self.esc_neutral = 0
      self.angle_mult = 0
      self.throt_mult = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.servo_neutral, _x.esc_neutral, _x.angle_mult, _x.throt_mult))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.servo_neutral, _x.esc_neutral, _x.angle_mult, _x.throt_mult,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.servo_neutral, _x.esc_neutral, _x.angle_mult, _x.throt_mult))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.servo_neutral, _x.esc_neutral, _x.angle_mult, _x.throt_mult,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
